### ISSUE TITLE
could I use inline keyboad on the fly with this package?

### ISSUE THREAD

**Issue by mrmrn** [noplanman/php-telegram-bot-manager#12]
hi,
thank you for the package.
could I use inline keyboard on the fly like [this](https://core.telegram.org/file/811140217/1/NkRCCLeQZVc/17a804837802700ea4)?

**Comment by noplanman** [comment]
Very soon!

https://github.com/akalongman/php-telegram-bot/pull/438

**Comment by noplanman** [comment]
A bit later than anticipated: [Inline Keyboard Pagination](https://github.com/php-telegram-bot/inline-keyboard-pagination)
