### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by noplanman** [noplanman/php-telegram-bot-manager#13]
Add ability to execute commands via cron.

@jacklul As I was implementing this, I thought I'd better open a discussion first 😊 

What do you think of this:
- Add a new action called `cron` (`php manager.php a=cron`)
- Add a new parameter called `cron_commands`

The parameter would be an array of commands, just like it's implemented in core now. So this would literally call `$telegram->runCommands($cron_commands);`

Do you see any other uses for cron at this moment?
Shall I opt for an array like this instead, to offer flexibility?
```php
$params = [
    'cron' => [
        'commands' => [...],
    ],
];
```

**Comment by jacklul** [comment]
Yes, `cron_commands` seems fine.

I was actually also going to suggest that some section became categorized.
This is how a config file for my bot looks like:

```php
$config = [
    // Basics
    'api_key'       => getenv('BOT_API_KEY'),
    'bot_username'  => getenv('BOT_USERNAME'),
    'secret'        => getenv('BOT_SECRET'),

    // Paths
    'paths'     => [
        'commands' => [
            ROOT_PATH . '/Commands/'
        ],
        'download' => ROOT_PATH . '/tmp/',
        'upload'   => ROOT_PATH . '/tmp/',
    ],

    // Database
    'mysql'     => [
        'host'     => getenv('DB_HOST'),
        'user'     => getenv('DB_USER'),
        'password' => getenv('DB_PASS'),
        'database' => getenv('DB_NAME'),
    ],

    // Webhook
    'webhook'   => [
        'url'               => getenv('BOT_WEBHOOK'),
        //'certificate'       => 'certificate.crt',
        'max_connections'   => 100,
        'allowed_updates'   => ['message', 'edited_message', 'inline_query', 'chosen_inline_result', 'callback_query'],
    ],

    // Logging
    'logging' => [
        'error'     => ROOT_PATH . '/logs/Error.log',
        //'debug'     => ROOT_PATH . '/logs/Debug.log',
        //'update'    => ROOT_PATH . '/logs/Update.log',
    ],

    // Settings
    'admins' => [(integer)getenv('BOT_ADMIN')],
    'command_configs' => [
        'randomcommand' => [
            'apikey' => getenv('randomcommandapikey'),
        ]
    ],

    // Extra features
    'botan' => [
        'token'     => getenv('BOTAN_TOKEN'),
        'options'    => [
            'timeout' => 1
        ],
    ],
    'limiter' => [
        'enabled' => true,
        'options' => [
            'interval' => 0.5,
        ],
    ],
    'cron_commands' => [
        '/cleanup',
        '/sendlogs',
    ],
];
```

Just throwing an idea!

**Comment by noplanman** [comment]
Nice, I really like the splitting up into sections. Makes it much easier to add additional features in the future.
At the same time I'd like to keep this project as easy-to-use as possible, which is the whole point I started it 😃 

I'm just wondering why you split them all up, but then you left `cron_commands`, instead of putting that into `'cron' => ['commands' => [...]]`.

Will do the split up then.
