### ISSUE TITLE
Install with PHP version < 7.0

### ISSUE THREAD

**Issue by golchi** [noplanman/php-telegram-bot-manager#32]
Hi,
Is it possible to have this work with a PHP version below 7.0 ?

Thanks.

**Comment by noplanman** [comment]
No, better you upgrade to PHP 7+ 😉 

Is there a specific reason why you need it for PHP 5?

**Comment by golchi** [comment]
I can't update my php version due to other projects; and online the server I want to use doesn't have PHP7 yet. I have downloaded a lower version as of now :-)

**Comment by noplanman** [comment]
Right, it should be quite easy to modify the code to make it PHP 5 compatible, but I intentionally made it PHP 7+ to force users to upgrade to the best PHP available.

If you really really need it, I might even do a PHP 5 branch for you, let me know.

Or, probably better, you clone this repo and make the changes required, then when you have a PHP 7 available, use the live master code.

**Comment by golchi** [comment]
I thought of digging the code to find out what was related to PHP7 and revert it back just to see all the updates of the latest version :-) If you can do that it will be helpful. Thanks in advance.

**Comment by noplanman** [comment]
Sticking with PHP 7...
