### ISSUE TITLE
Restrictive bot access

### ISSUE THREAD

**Issue by noplanman** [noplanman/php-telegram-bot-manager#33]
(From https://github.com/php-telegram-bot/core/issues/527)

Would be cool to implement this as an ultimate firewall, before the bot code is even touched.
Although, it could also be cool to have it just after initialisation, so that rules could be configured via commands.

Hmmm.... 🤔 

@jacklul Ideas very welcome as always!

**Comment by jacklul** [comment]
I guess simple access filtering by basic fields like chat and user ID should be fine, also the maintenance mode letting admins still use the bot and other users not.
