### ISSUE TITLE
Update Message: deactivate sql write

### ISSUE THREAD

**Issue by andrenjdev** [noplanman/php-telegram-bot-manager#37]
Hi,
I have to remove update in sql Db only when i do editMessage command because the level of cpu is always over 80% and sometime it go down :/
Can you say me how to deactivate this feature? I have to edit Request file?

Thank you for your great work.

Andrea

**Comment by noplanman** [comment]
Hi, could you please explain in more detail what your are doing that causes this?

Of course it would make sense to fix the problem for everyone, not just remove the code in your personal project 👍

**Comment by andrenjdev** [comment]
It's not a problem but my costumer start a process at the same time and this process update every minutes a message. 
I have a small server on AWS and every day the CPU level is over 80%. I wish to deactivate the writing on my db to improve the service. I can edit the message without store it on db?

Thanks

**Comment by jacklul** [comment]
This gives me idea to have some kind of options for the DB to select which tables to insert to. 

PS. You can copy DB.php from the core library into your project then either autoload it with composer or include/require in hook script, then you can remove the query that inserts edited message from there, this is mostly a workaround but should do what you want. You will have to watch for DB.php updates in the future to not break the bot.

**Comment by noplanman** [comment]
@jacklul I really like that idea!

**Comment by andrenjdev** [comment]
So, 

````
elseif ($update_type === 'edited_message') {
            $edited_message = $update->getEditedMessage();

            if (self::insertEditedMessageRequest($edited_message)) {
                $chat_id                 = $edited_message->getChat()->getId();
                $edited_message_local_id = self::$pdo->lastInsertId();

                return self::insertTelegramUpdate(
                    $update_id,
                    $chat_id,
                    null,
                    null,
                    null,
                    null,
                    $edited_message_local_id
                );
            }
        }
````
I can edit it and do that, it works?

````
elseif ($update_type === 'edited_message') {
            $edited_message = $update->getEditedMessage();

            return true;
        }
````
Could be a correct solution?
Thank you :)

**Comment by jacklul** [comment]
Yes but putting `return true;` just after `elseif ($update_type === 'edited_message') {` would be better, no need to execute any code before that.

**Comment by andrenjdev** [comment]
@jacklul thanks a lot
You make my day :)

**Comment by andrenjdev** [comment]
@noplanman @jacklul 
<img width="249" alt="schermata 2017-08-12 alle 19 03 59" src="https://user-images.githubusercontent.com/3781468/29243183-10932d26-7f91-11e7-8eaf-0bd779d087dd.png">

This is the CPU Utilization Percent chart. Are you sure that this patch can be the right solution?
My DB went down again :(

**Comment by jacklul** [comment]
The patch does what you wanted, prevents inserting edited messages to the database.

There might be some misconfiguration error on the database server or something. 
As far as I can tell, the library itself doesn't spike that much on CPU usage on very active bots.

**Comment by andrenjdev** [comment]
I improved my db and my code. I will update you. thank you:)

**Comment by andrenjdev** [comment]
Hei,
the problem still exist so I improved the database CPU power. I have seen that the size table named: request_limiter is 264 MB  (after 1 month of time-live ) and every minutes the number of row increase by 100 rows.

**Comment by jacklul** [comment]
Yes, every request that can cause a bot to get limited by the API is inserted there, you can set up a SQL task to clean that table from records older than 5 minutes, that will make the trick!

**Comment by andrenjdev** [comment]
I think it's not a solution for my problem but I can try to add this task :)
