### ISSUE TITLE
installing with composer

### ISSUE THREAD

**Issue by Theolodewijk** [noplanman/php-telegram-bot-manager#54]
]# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-telegram-bot/telegram-bot-manager 1.5.0 requires longman/telegram-bot ^0.59 -> satisfiable by longman/telegram-bot[0.59.0, 0.59.1] but these conflict with your requirements or minimum-stability.
    - php-telegram-bot/telegram-bot-manager 1.4.0 requires longman/telegram-bot ^0.57 -> satisfiable by longman/telegram-bot[0.57.0] but these conflict with your requirements or minimum-stability.
    - Installation request for php-telegram-bot/telegram-bot-manager ^1.4 -> satisfiable by php-telegram-bot/telegram-bot-manager[1.4.0, 1.5.0].

**Comment by jacklul** [comment]
Could you post contents of your composer.json?

**Comment by noplanman** [comment]
@Theolodewijk Note, due to the unstable versioning, you'll need something like this for use with newer core versions:
```json
"require": {
    "php-telegram-bot/telegram-bot-manager": "^1.5",
    "longman/telegram-bot": "dev-master as 0.59"
}
```

**Comment by Theolodewijk** [comment]
```{
    "require": {
        "phpmailer/phpmailer": "^6.1",
        "twbs/bootstrap": "^4.4",
        "verot/class.upload.php": "^2.0",
        "tinymce/tinymce": "^5.2",
        "datatables/datatables": "^1.10",
        "components/jquery": "^3.4",
        "components/highlightjs": "^9.16",
        "nnnick/chartjs": "^2.9",
        "components/font-awesome": "^5.12",
        "zenorocha/clipboardjs": "^2.0",
        "php-telegram-bot/telegram-bot-manager": "^1.5",
        "longman/telegram-bot": "^0.61.1",
        "harvesthq/chosen": "^1.8",
        "facebook/graph-sdk": "^5.7",
        "unreal4u/telegram-api": "^3.5"
    },
}```

returns 

# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-telegram-bot/telegram-bot-manager ^1.5 -> satisfiable by php-telegram-bot/telegram-bot-manager[1.5.0].
    - php-telegram-bot/telegram-bot-manager 1.5.0 requires longman/telegram-bot ^0.59 -> satisfiable by longman/telegram-bot[0.59.0, 0.59.1] but these conflict with your requirements or minimum-stability.

[root@mail

**Comment by noplanman** [comment]
@Theolodewijk Please read my comment above again...

Instead of
`"longman/telegram-bot": "^0.61.1"`
you need to put
`"longman/telegram-bot": "0.61.1 as 0.59"`

Or whatever version you want.

**Comment by Gabo1122** [comment]
**I'm still having the same error:**
 - The requested package php-telegram-bot/telegram-bot-manager No version set (parsed as 1.0.0) is satisfiable by php-telegram-bot/telegram-bot-manager[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


**I tried this already:**


> @Theolodewijk Please read my comment above again...
> 
> Instead of
> "longman/telegram-bot": "^0.61.1"
> you need to put
> "longman/telegram-bot": "0.61.1 as 0.59"
> 
> Or whatever version you want.

**But the same thing happens**

**I then changed my composer.json to this:** 

```json
{
    "name": "php-telegram-bot/telegram-bot-manager",
    "type": "library",
    "description": "PHP Telegram Bot Manager",
    "keywords": ["telegram", "bot", "manager"],
    "license": "MIT",
    "homepage": "https://github.com/php-telegram-bot/telegram-bot-manager",
    "support": {
        "issues": "https://github.com/php-telegram-bot/telegram-bot-manager/issues",
        "source": "https://github.com/php-telegram-bot/telegram-bot-manager"
    },
    "authors": [
        {
            "name": "Armando Lüscher",
            "email": "armando@noplanman.ch",
            "homepage": "https://noplanman.ch",
            "role": "Developer"
        }
    ],
    "require": {
        "php": "^7.1",
        "php-telegram-bot/telegram-bot-manager": "^1.5",
        "longman/telegram-bot": "0.59.1",
        "longman/ip-tools": "^1.2",
        "psr/log": "^1.1"
    },
    "require-dev": {
        "jakub-onderka/php-parallel-lint": "^1.0",
        "phpunit/phpunit": "^7.5|^8.2",
        "squizlabs/php_codesniffer": "^3.4"
    },
    "autoload": {
        "psr-4": {
            "TelegramBot\\TelegramBotManager\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "TelegramBot\\TelegramBotManager\\Tests\\": "tests"
        }
    },
    "scripts": {
        "check-code": [
            "vendor/bin/parallel-lint . --exclude vendor",
            "vendor/bin/phpcs -snp src/ tests/"
        ],
        "test": [
            "vendor/bin/phpunit --exclude-group live"
        ],
        "test-live": [
            "vendor/bin/phpunit"
        ],
        "test-cov": [
            "vendor/bin/phpunit --coverage-clover coverage.xml --exclude-group live"
        ],
        "test-cov-live": [
            "vendor/bin/phpunit --coverage-clover coverage.xml"
        ],
        "test-cov-upload": [
            "curl -s https://codecov.io/bash | bash"
        ]
    }
}
```

**But then I get this error:**

 Problem 1
    - The requested package php-telegram-bot/telegram-bot-manager No version set (parsed as 1.0.0) is satisfiable by php-telegram-bot/telegram-bot-manager[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by noplanman** [comment]
Hi @Gabo1122 

You shouldn't copy the `composer.json` of the project itself, but instead create your own one.

A minimal starting point for you would be this:
```json
{
    "require": {
        "php-telegram-bot/telegram-bot-manager": "^1.5",
        "longman/telegram-bot": "0.63.1 as 0.59.1"
    }
}
```

Then just do `composer install` to download the necessary library files.

**Comment by jfcherng** [comment]
But why we have to lock `longman/telegram-bot` with `0.59.x`? Is this package not compatible with `0.63.1`?
https://github.com/php-telegram-bot/telegram-bot-manager/blob/35ca6cf6d17b752416610dd5d67cdd222dab71f2/composer.json#L22

~~Okay... it does not compatible indeed~~

**Comment by noplanman** [comment]
@jfcherng Yes, it is compatible, as described in the comment just above yours.

**Comment by jfcherng** [comment]
> @jfcherng Yes, it is compatible, as described in the comment just above yours.

My apology. I jump into the conclusion too soon without going through `longman/telegram-bot`'s changelog. The major problem I faced is due to the monolog deprecation. But with your great migration guide in https://github.com/php-telegram-bot/core/pull/964#issue-286371074, my bot works well with `0.63.1` now :smiley:  Thanks!
