### ISSUE TITLE
add extra parameters in hook Url

### ISSUE THREAD

**Issue by damianperez** [noplanman/php-telegram-bot-manager#58]
### Feature Request
add extra parameters in hook Url
#### Summary

You can't manage extra parameters in webhook beacouse the '?'.
$this->handleOutput(
$this->telegram->setWebhook(
$webhook['url'] . '?a=handle&s=' . $this->params->getBotParam('secret'),
$webhook_params
)->getDescription() . PHP_EOL
);

May be good that if webhook url has a parameter, then add a '&'
to do this:
manager.php?Myparam=123&a=handle&s=supersecret

**Comment by noplanman** [comment]
@damianperez Great idea! Care to make a PR for this? 😊

**Comment by damianperez** [comment]
Hi @noplanman ! 
Hi all,

I realized that having multiple bots running involves constantly updating code and hooks.  
So I think I need a manager.php that can manipulate various bots. 
But:  
Thinking about it deeply, I think I'm going to raise this issue because the extra parameter may be the 'secret' parameter. I am already implementing it passing as secret the md5 of some data of my bots (such as the id or the botname).   
So I can read the secret to know which bot I have to handle.  
 
So now the question is: How do I delete this issue? 😊

**Comment by noplanman** [comment]
I still think it's a great idea to allow extra parameters, which is clearly a limitation now.

So even if you've found a different way of solving this for your use-case, I'll leave this issue open :+1:

(P.S. You can't delete issues or PRs on GitHub, you can only close them)

**Comment by damianperez** [comment]
Ok. I don't know how to do the modification here ( i must to learn ) but the solution is:
_in BotManager.php Line:239_
 **$webhook['url'] .= ( isset(parse_url($webhook['url'])['query'])) ? '&' : '?' ;**  
 $this->handleOutput(  $this->telegram->setWebhook($webhook['url'] **. 'a=handle**&s=' . $this->params->getBotParam('secret'),  $webhook_params  )->getDescription() . PHP_EOL        );
