### ISSUE TITLE
telegram_bot.ERROR: cURL error 28: Failed to connect to api.telegram.org port 443

### ISSUE THREAD

**Issue by reactmore** [noplanman/php-telegram-bot-manager#66]
### Support Question

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                               |  !
| ---                              | ---
| Operating system                 | Name and version
| PHP Telegram Bot Manager version | x.y.z
| PHP Telegram Bot version         | x.y.z
| PHP version                      | x.y.z
| MySQL version                    | x.y.z / none
| Update Method                    | Webhook / getUpdates
| Self-signed certificate          | yes / no
| RAW update (if available)        | `{...}`

#### Summary

if i use manager package alwasy get this log and bot not running
telegram_bot.ERROR: cURL error 28: Failed to connect to api.telegram.org port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.telegram.org/botxxxxx:tokenbot/setWebhook []

 any suggestion to fix this sir ?

**Comment by jacklul** [comment]
Is the server you're hosting the bot on able to reach api.telegram.org?
If you're in Telegram banned country you will have to use a proxy - https://github.com/php-telegram-bot/core/issues/667#issuecomment-334851805

**Comment by reactmore** [comment]
> Is the server you're hosting the bot on able to reach api.telegram.org?
> If you're in Telegram banned country you will have to use a proxy - [php-telegram-bot/core#667 (comment)](https://github.com/php-telegram-bot/core/issues/667#issuecomment-334851805)

Sure is no problem if use basic method like
https://api.telegram.org/bot{my_bot_token}/setWebhook?url=domain path to webhook.php

My country not banned telegram

**Comment by jacklul** [comment]
> Sure is no problem if use basic method like
> [https://api.telegram.org/bot{my_bot_token}/setWebhook?url=domain](https://api.telegram.org/bot%7Bmy_bot_token%7D/setWebhook?url=domain) path to webhook.php

Through curl?

**Comment by jacklul** [comment]
@reactmore  Did you manage to fix the issue?

**Comment by Naveenjangraje** [comment]
@reactmore bro I need some help please about AddChat Codeigniter please help me

**Comment by jacklul** [comment]
I am closing this issue as OP didn't reply for a long time...
