### ISSUE TITLE
telegram-bot-manager 1.6.0 requires longman/telegram-bot ^0.70

### ISSUE THREAD

**Issue by massadm** [noplanman/php-telegram-bot-manager#67]
longman/telegram-bot 0.71.0 is out

**Comment by noplanman** [comment]
Hi @massadm, the manager project doesn't follow every release of the core library at the moment.

You can still make use of the latest version in your project though! In your `composer.json` file, just put the following:
```json
"require": {
    "php-telegram-bot/telegram-bot-manager": "^1.6",
    "longman/telegram-bot": "dev-develop as 0.71"
}
```

I'll release a new version of the manager in the coming days though, to also include your latest fix 🙏

**Comment by massadm** [comment]
I decided to refrain from forcibly updating the core library because I can't imagine all the side effects. I'll wait for the official update. Thanks! :-)

**Comment by noplanman** [comment]
@massadm You can get version 1.7.0 now, with the newest version of core, 0.73.0 🎉
