### ISSUE TITLE
Cannot disable MySQL dependency when using BotManager

### ISSUE THREAD

**Issue by oliveratgithub** [noplanman/php-telegram-bot-manager#71]
### Support Question
Using the instructions to disable MySQL dependency in `manager.php` via `$bot->useGetUpdatesWithoutDatabase()` is not working. This seems to be a setter method only working with the Longman PHP Telegram Bot Class. But such is initiated only when using Webhooks (e.g. in `hooks.php`).

How can I disable the MySQL dependency when using the Bot Manager / manager.php?

#### Required Information

PHP 7.4
Telegram Bot Manager 1.7

#### Summary
From the Telegram PHP Bot/core documentation:

> ##### getUpdates without database
> 
> If you choose to / or are obliged to use the getUpdates method without a database, you can replace the `$telegram->useMySQL(...);` line above with:
> 
> `$telegram->useGetUpdatesWithoutDatabase();`
>

**Comment by noplanman** [comment]
Hi @oliveratgithub 

To call methods directly on the Telegram object, you can do the following:
```php
$bot = new BotManager($yourConfig);
$bot->getTelegram()->useGetUpdatesWithoutDatabase();
$bot->run();
```

**Comment by oliveratgithub** [comment]
@noplanman Awesome, works like a charm! Thanks a lot
