### ISSUE TITLE
 run php manager.php ,but mywebhock can't recive any messages.

### ISSUE THREAD

**Issue by jishuXiaom** [noplanman/php-telegram-bot-manager#72]
### Bug Report

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                               |  !
| ---                              | ---
| Operating system                 | centos  7.9.2009 
| PHP Telegram Bot Manager version |  1.7.0
| PHP Telegram Bot version         | 0.73.0
| PHP version                      | 7.4
| MySQL version                    | 5.7 / none
| Update Method                    | Webhook 
| Self-signed certificate          | no
| RAW update (if available)        | `{...}`

#### How to reproduce
 run php manager.php ,but mywebhock can't recive any messages.

**Comment by noplanman** [comment]
Did you set the webhook correctly first?

`php manager.php a=set`

**Comment by Odilbukh** [comment]
![image](https://user-images.githubusercontent.com/22895615/176827354-7567f038-5efc-4239-b916-8804157a7b94.png)

Me too facing such error

**Comment by noplanman** [comment]
Hi, I've just released version 2.0.0, please try again.
