### ISSUE TITLE
Support latest telegram bot API improvements

### ISSUE THREAD

**Issue by juliustm** [noplanman/php-telegram-bot-manager#73]
### Feature Request
Support telegram web app feature offered by the latest telegram API.
### Summary
Documentation of the requested feature  can be found here -> [https://core.telegram.org/bots/webapps](url)

**Comment by noplanman** [comment]
Hi @juliustm, the latest Bot API 6.0 update has been added to the core library in version 0.77.1.

You can update your `composer.json` to use the latest version like this:
```json
"require": {
    "php-telegram-bot/telegram-bot-manager": "^1.6",
    "longman/telegram-bot": "0.77.1 as 0.70"
}
```
Remember to run `composer update` after making the change!

**Comment by juliustm** [comment]
> Hi @juliustm, the latest Bot API 6.0 update has been added to the core library in version 0.77.1.
> 
> You can update your `composer.json` to use the latest version like this:
> 
> ```json
> "require": {
>     "php-telegram-bot/telegram-bot-manager": "^1.6",
>     "longman/telegram-bot": "0.77.1 as 0.70"
> }
> ```
> 
> Remember to run `composer update` after making the change!

Thanks for your response @noplanman
